### PR TITLE
Change topic

### PR DESCRIPTION
**Pull request by tt**

### CODE REVIEW

**Comment by hunterloftis** [comment]
Tested with alpine linux + node docker image and:

```
$ heroku container:login
$ heroku container:push
```

👍  lgtm

**Comment by hunterloftis** [comment]
Before we publish, we should bump the version to 3.0.0 (as this is a breaking API change).

**Comment by tt** [comment]
@hunterloftis, is it really breaking when we renamed the package?

**Comment by hunterloftis** [comment]
It won't technically break anything, but I would really like to stick to semver since this is really a continuation of the same package. Alternatively, we could start over at 1.0.

**Pull request merged**
