### PR TITLE
restore deprecated commands

### PR DESCRIPTION
**Pull request by hunterloftis**
Restores `:init` and `:release`

### CODE REVIEW

**Comment by jbyrum** [comment]
LGTM

**Comment by jesperfj** [comment]
@hunterloftis can you update the README too so it doesn't say "Heroku Docker" or anything of the sorts?

**Comment by hunterloftis** [comment]
@jesperfj can do!

**Comment by hunterloftis** [comment]
@jesperfj want to check it over for a 👍  ?

**Comment by jesperfj** [comment]
👍

**Pull request merged**
